server:
  port: 10010
spring:
  application:
    name: spring-cloud-eureka
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 1000
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:10010/eureka/
    healthcheck:
      enabled: true
