server:
  port: 20010
spring:
  application:
    name: spring-cloud-order-20010
  datasource:
    driver-class-name:
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://localhost:10010/eureka/,http://localhost:10020/eureka/
    healthcheck:
      enabled: true