spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  cloud:
    loadbalancer:
      retry:
        enabled: false
    sentinel:
      filter:
        enabled: false
      transport:
        dashboard: sentinel.xueyongxiangzhang.com
        port: 8719
        clientIp: 139.196.178.196
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  type-aliases-package: com.spring.cloud.study.order.model
  mapper-locations: classpath:com/spring/cloud/study/order/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
management:
  endpoints:
    web:
      exposure:
        include: "*"