server:
  port: 20010
spring:
  application:
    name: spring-cloud-order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.196.178.196:3306/spring_cloud_test?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: cyinfo666888666
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  cloud:
    loadbalancer:
      retry:
        enabled: false
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  type-aliases-package: com.spring.cloud.study.order.model
  mapper-locations: classpath:com/spring/cloud/study/order/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
ribbon:
  eureka:
    enabled: true
eureka:
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:10010/eureka/
    healthcheck:
      enabled: true
feign:
  client:
    config:
      default:
        # 建立连接所用的时间，适用于网络状况正常的情况下，两端连接所需要的时间
        ConnectionTimeout: 5000
        # 指建立连接后从服务端读取到可用资源所用的时间
        ReadTimeout: 10000
  hystrix:
    enabled: true
logging:
  level:
    root: info
    com.spring.cloud.study: debug
#暴露全部的监控信息
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: hystrix.stream