spring:
  cloud:
    nacos:
      config:
        namespace: ceafee46-637c-4306-a5bf-e95e83179927
      discovery:
        namespace: ceafee46-637c-4306-a5bf-e95e83179927
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.196.178.196:3306/spring_cloud_test?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: cyinfo666888666
feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        # 建立连接所用的时间，适用于网络状况正常的情况下，两端连接所需要的时间
        ConnectionTimeout: 5000
        # 指建立连接后从服务端读取到可用资源所用的时间
        ReadTimeout: 10000
server:
  port: 20010
logging:
  level:
    root: info
    com.spring.cloud.study: debug