spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  cloud:
    loadbalancer:
      retry:
        enabled: false
    sentinel:
      filter:
        enabled: false
      transport:
        dashboard: 139.196.178.196:10110
        port: 8719
        clientIp: 139.196.178.196
management:
  endpoints:
    web:
      exposure:
        include: "*"
