spring:
  cloud:
    nacos:
      config:
        namespace: ceafee46-637c-4306-a5bf-e95e83179927
      discovery:
        namespace: ceafee46-637c-4306-a5bf-e95e83179927
feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        # 建立连接所用的时间，适用于网络状况正常的情况下，两端连接所需要的时间
        ConnectionTimeout: 5000
        # 指建立连接后从服务端读取到可用资源所用的时间
        ReadTimeout: 10000
server:
  port: 8001
logging:
  level:
    root: info
    com.spring.cloud.study: debug