spring:
  cloud:
    nacos:
      config:
        namespace: adb1a97b-a759-4386-bc60-648879530f0e
      discovery:
        namespace: adb1a97b-a759-4386-bc60-648879530f0e
feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        # 建立连接所用的时间，适用于网络状况正常的情况下，两端连接所需要的时间
        ConnectionTimeout: 5000
        # 指建立连接后从服务端读取到可用资源所用的时间
        ReadTimeout: 10000
server:
  port: 8001
logging:
  level:
    root: info
    com.spring.cloud.study: debug