server:
  port: 8001
spring:
  application:
    name: spring-cloud-portal
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
eureka:
  instance:
    instance-id: ${spring.application.name}-${random.uuid}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:10010/eureka/
    healthcheck:
      enabled: true
feign:
  httpclient:
    connection-timeout: 5000
ribbon:
  eureka:
    enabled: true